### ISSUE TITLE
editor.css is no longer used

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe-themes/silverstripe-simple#68]
In SilverStripe 4.x the simple theme is not enabled for HTMLEditorConfig any longer, so the rule in the file is not applied to TinyMCE instances in the CMS any longer:

```css
/**
 * This support file is used to style the WYSIWYG editor in the CMS
 */

@import "typography.css?2";
body.mceContentBody{font-size:13px;}
```

We may consider either removing the file or re-enabling it again.
